using System.Xml;
using System.Text;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Collections.ObjectModel;

[Generator]
public sealed class CSharpVulkanBindingsGenerator : IIncrementalGenerator
{
  private static readonly DiagnosticDescriptor noVkXmlFileDiagnostic = new(
    id: "VK0001",
    title: "No Vulkan API description file has been provided",
    messageFormat: "Add '{0}' to AdditionalFiles in the .csproj of the consumer of `VulkanBindingsGenerator`",
    category: "Usage",
    defaultSeverity: DiagnosticSeverity.Warning,
    isEnabledByDefault: true
  );
  private static readonly DiagnosticDescriptor multipleVkXmlFilesDiagnostic = new(
    id: "VK0002",
    title: "Only one Vulkan API description file is allowed to be provided",
    messageFormat: "Remove redundant '{0}' files from AdditionalFiles of the .csproj of the consumer of `VulkanBindingsGenerator`",
    category: "Usage",
    defaultSeverity: DiagnosticSeverity.Warning,
    isEnabledByDefault: true
  );

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    var files = context.AdditionalTextsProvider.Where(file => Path.GetFileName(file.Path).Equals("vk.xml",StringComparison.InvariantCulture));
    context.RegisterSourceOutput(context.CompilationProvider.Combine(files.Collect()),static (context,pair) =>
    {
      if(pair.Right.Length == 0)
      {
        context.ReportDiagnostic(Diagnostic.Create(noVkXmlFileDiagnostic,null,"vk.xml"));
        return;
      }
      if(pair.Right.Length > 1)
      {
        context.ReportDiagnostic(Diagnostic.Create(multipleVkXmlFilesDiagnostic,null,"vk.xml"));
        return;
      }
      var vkDocument = new XmlDocument();
      vkDocument.Load(pair.Right[0].Path);
      var vkData = VulkanHeaderData.CreateFrom(vkDocument);
      BuildOutputFile(context,vkData,"Vulkan.g.cs");
    });
  }

  private static void BuildOutputFile(SourceProductionContext context,VulkanHeaderData data,string fileName)
  {
    StringBuilder builder = new();
    builder.AppendLine("/// <auto-generated>");
    builder.AppendLine("/// Auto-generated Vulkan bindings.");
    builder.AppendLine("/// Don't modify this file directly, as all your changes will be overwritten when the source generator runs again.");
    builder.AppendLine("/// </auto-generated>");
    builder.AppendLine();

    builder.AppendLine("namespace TheHyper45.CSharpVulkanBindings;");
    builder.AppendLine();
    builder.AppendLine("public static class Vulkan {");
    {
      builder.AppendLine("\tpublic static uint VK_MAKE_API_VERSION(uint variant,uint major,uint minor,uint patch) => (variant << 29) | (major << 22) | (minor << 12) | patch;");
      builder.AppendLine("\tpublic static uint VK_API_VERSION_VARIANT(uint version) => version >> 29;");
      builder.AppendLine("\tpublic static uint VK_API_VERSION_MAJOR(uint version) => (version >> 22) & 0x7F;");
      builder.AppendLine("\tpublic static uint VK_API_VERSION_MINOR(uint version) => (version >> 12) & 0x3FF;");
      builder.AppendLine("\tpublic static uint VK_API_VERSION_PATCH(uint version) => version & 0xFFF;");
      builder.AppendLine("\tpublic static readonly uint VK_API_VERSION_1_0 = VK_MAKE_API_VERSION(0,1,0,0);");
      builder.AppendLine("\tpublic static readonly uint VK_API_VERSION_1_1 = VK_MAKE_API_VERSION(0,1,1,0);");
      builder.AppendLine("\tpublic static readonly uint VK_API_VERSION_1_2 = VK_MAKE_API_VERSION(0,1,2,0);");
      builder.AppendLine("\tpublic static readonly uint VK_API_VERSION_1_3 = VK_MAKE_API_VERSION(0,1,3,0);");
      builder.AppendLine("\tpublic static readonly uint VK_API_VERSION_1_4 = VK_MAKE_API_VERSION(0,1,4,0);");
      builder.AppendLine();

      foreach(var constant in data.constants)
      {
        builder.AppendLine($"\tpublic const {constant.Value.type} {constant.Key} = {constant.Value.value};");
      }
      builder.AppendLine("\tpublic const string VK_LAYER_KHRONOS_VALIDATION = \"VK_LAYER_KHRONOS_validation\";");
      builder.AppendLine();

      foreach(var typeAlias in data.typeAliases)
      {
        builder.AppendLine($"\tpublic struct {typeAlias.Key}({typeAlias.Value} _value) {{");
        builder.AppendLine($"\t\tpublic {typeAlias.Value} value = _value;");
        builder.AppendLine($"\t\tpublic static implicit operator {typeAlias.Key}({typeAlias.Value} key) => new(key);");
        builder.AppendLine($"\t\tpublic static implicit operator {typeAlias.Value}({typeAlias.Key} key) => key.value;");
        builder.AppendLine("\t}");
      }
      builder.AppendLine();

      foreach(var handle in data.handles)
      {
        var handleType = handle.Value ? "ulong" : "nint";
        builder.AppendLine($"\tpublic struct {handle.Key}({handleType} _value) : global::System.IEquatable<{handle.Key}> {{");
        builder.AppendLine($"\t\tpublic {handleType} value = _value;");
        builder.AppendLine($"\t\tpublic static readonly {handle.Key} Null = new(0);");
        builder.AppendLine($"\t\tpublic override int GetHashCode() => value.GetHashCode();");
        builder.AppendLine($"\t\tpublic override bool Equals(object? obj) => obj is {handle.Key} handle && Equals(handle);");
        builder.AppendLine($"\t\tpublic bool Equals({handle.Key} other) => other.value == value;");
        builder.AppendLine($"\t\tpublic static bool operator ==({handle.Key} a,{handle.Key} b) => a.Equals(b);");
        builder.AppendLine($"\t\tpublic static bool operator !=({handle.Key} a,{handle.Key} b) => !(a == b);");
        builder.AppendLine("\t}");
      }
      builder.AppendLine();

      foreach(var @enum in data.enums)
      {
        if(@enum.Value.isFlags) builder.AppendLine($"\t[global::System.Flags]");
        builder.AppendLine($"\tpublic enum {@enum.Key} : {@enum.Value.underlyingType} {{");
        foreach(var enumMember in @enum.Value.members)
        {
          builder.AppendLine($"\t\t{enumMember.Key} = {enumMember.Value},");
        }
        builder.AppendLine("\t}");
      }
      builder.AppendLine();

      foreach(var funcPointer in data.funcPointers)
      {
        builder.AppendLine($"\tpublic unsafe struct {funcPointer.Key}({funcPointer.Value.delegateUnmanagedString} _ptr = null) {{");
        builder.AppendLine($"\t\tpublic {funcPointer.Value.delegateUnmanagedString} ptr = _ptr;");
        builder.AppendLine($"\t\tpublic static explicit operator {funcPointer.Key}(nint key) => new(({funcPointer.Value.delegateUnmanagedString})key);");
        if(funcPointer.Key != "PFN_vkVoidFunction")
        {
          builder.AppendLine($"\t\tpublic static explicit operator {funcPointer.Key}(PFN_vkVoidFunction key) => new(({funcPointer.Value.delegateUnmanagedString})key.ptr);");
        }
        builder.AppendLine($"\t\tpublic static implicit operator {funcPointer.Key}({funcPointer.Value.delegateUnmanagedString} key) => new(key);");
        builder.AppendLine($"\t\tpublic static implicit operator {funcPointer.Value.delegateUnmanagedString}({funcPointer.Key} key) => key.ptr;");
        builder.AppendLine("\t}");
      }
      builder.AppendLine();

      foreach(var @struct in data.structs)
      {
        if(@struct.Value.isUnion)
        {
          builder.AppendLine("\t[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]");
        }
        builder.AppendLine($"\tpublic struct {@struct.Key} {{");

        int bitfieldBackingFieldIndex = 0;
        for(int memberI = 0;memberI < @struct.Value.members.Count;memberI += 1)
        {
          var structMember = @struct.Value.members[memberI];

          if(structMember.bitFields != null)
          {
            int bitfieldsOffset = 0;
            int lastBitfieldIndex = memberI;
            for(;lastBitfieldIndex < @struct.Value.members.Count;lastBitfieldIndex += 1)
            {
              var bitfield = @struct.Value.members[lastBitfieldIndex];
              if(bitfield.bitFields == null)
              {
                lastBitfieldIndex -= 1;
                break;
              }
              var bitfieldSize = int.Parse(bitfield.bitFields);
              builder.AppendLine($"\t\tpublic {bitfield.type} {bitfield.name} {{");
              builder.AppendLine($"\t\t\tget => ({bitfield.type})((_bitfield{bitfieldBackingFieldIndex} >> {bitfieldsOffset}) & {bitfieldSize});");
              builder.AppendLine($"\t\t\tset => _bitfield{bitfieldBackingFieldIndex} |= ((uint)value & {bitfieldSize}) << {bitfieldsOffset};");
              builder.AppendLine("\t\t}");
              bitfieldsOffset += bitfieldSize;
              if(bitfieldsOffset == 32) break;
            }

            memberI = lastBitfieldIndex;
            if(@struct.Value.isUnion)
            {
              builder.AppendLine("\t\t[global::System.Runtime.InteropServices.FieldOffset(0)]");
            }
            builder.AppendLine($"\t\tpublic uint _bitfield{bitfieldBackingFieldIndex};");
            bitfieldBackingFieldIndex += 1;
            continue;
          }

          var canBeUsedInFixedBuffer = data.typesThatCanBeUsedInFixedBuffers.Contains(structMember.type);
          var isPointer = structMember.type.Contains('*');
          if(structMember.arraySize != null && !canBeUsedInFixedBuffer)
          {
            builder.AppendLine($"\t\t[global::System.Runtime.CompilerServices.InlineArray((int){structMember.arraySize})]");
            builder.AppendLine($"\t\tpublic struct {structMember.name}_InlineArray {{");
            builder.AppendLine($"\t\t\tpublic {structMember.type} _element0;");
            builder.AppendLine("\t\t}");
          }
          if(@struct.Value.isUnion)
          {
            builder.AppendLine("\t\t[global::System.Runtime.InteropServices.FieldOffset(0)]");
          }
          if(structMember.arraySize == null && !isPointer)
          {
            builder.AppendLine($"\t\tpublic {structMember.type} {structMember.name};");
          }
          else if(structMember.arraySize == null && isPointer)
          {
            builder.AppendLine($"\t\tpublic unsafe {structMember.type} {structMember.name};");
          }
          else if(structMember.arraySize != null && canBeUsedInFixedBuffer)
          {
            builder.AppendLine($"\t\tpublic unsafe fixed {structMember.type} {structMember.name}[(int){structMember.arraySize}];");
          }
          else if(structMember.arraySize != null && !canBeUsedInFixedBuffer)
          {
            builder.AppendLine($"\t\tpublic {structMember.name}_InlineArray {structMember.name};");
          }
        }
        builder.AppendLine("\t}");
      }
      builder.AppendLine();
      /*builder.AppendLine("\tpublic sealed class VulkanException(VkResult _result) : Exception($\"result = {_result}\") {");
			builder.AppendLine("\t\tpublic VkResult Result => _result;");
			builder.AppendLine("\t}");

			builder.AppendLine();
			builder.AppendLine("\tpublic sealed class VulkanCriticalException(VkResult _result) : Exception($\"result = {_result}\") {");
			builder.AppendLine("\t\tpublic VkResult Result => _result;");
			builder.AppendLine("\t}");

			builder.AppendLine();
			builder.AppendLine("\tpublic static VkResult VulkanCheck(VkResult result) {");
			builder.AppendLine("\t\tif(result == VkResult.VK_ERROR_DEVICE_LOST || result == VkResult.VK_ERROR_OUT_OF_DEVICE_MEMORY || result == VkResult.VK_ERROR_OUT_OF_HOST_MEMORY) throw new VulkanCriticalException(result);");
			builder.AppendLine("\t\treturn (result == VkResult.VK_SUCCESS) ? result : throw new VulkanException(result);");
			builder.AppendLine("\t}");
			builder.AppendLine();*/

      /*builder.AppendLine("\tpublic static uint? VulkanFindMemoryTypeIndex(ref VkPhysicalDeviceMemoryProperties props,uint memoryTypeBits,VkMemoryPropertyFlagBits flagBits) {");
			builder.AppendLine("\t\tfor(uint i = 0;i < props.memoryTypeCount;i += 1) {");
			builder.AppendLine("\t\t\tvar correctIndex = (memoryTypeBits & (1u << (int)i)) == (1u << (int)i);");
			builder.AppendLine("\t\t\tvar correctFlags = ((VkMemoryPropertyFlagBits)props.memoryTypes[(int)i].propertyFlags & flagBits) == flagBits;");
			builder.AppendLine("\t\t\tif(correctIndex && correctFlags) return i;");
			builder.AppendLine("\t\t}");
			builder.AppendLine("\t\treturn null;");
			builder.AppendLine("\t}");
			builder.AppendLine();*/

      builder.AppendLine("\tpublic static ulong VulkanFormatByteSize(VkFormat format) {");
      builder.AppendLine("\t\treturn format switch {");
      foreach(var formatPair in data.formatSizes)
      {
        builder.AppendLine($"\t\t\tVkFormat.{formatPair.Key} => {formatPair.Value},");
      }
      builder.AppendLine("\t\t\tvar _ => 0");
      builder.AppendLine("\t\t};");
      builder.AppendLine("\t}");
      builder.AppendLine();

      /*builder.AppendLine("\tpublic static unsafe bool VulkanHasInstanceLayer(VulkanGlobalOnlyDispatch dispatch,string name) {");
			builder.AppendLine("\t\tuint layerCount = 0;");
			builder.AppendLine("\t\tVulkanCheck(dispatch.vkEnumerateInstanceLayerProperties(&layerCount,null));");
			builder.AppendLine("\t\tvar layerProperties = new VkLayerProperties[layerCount];");
			builder.AppendLine("\t\tfixed(VkLayerProperties* ptr = layerProperties) {");
			builder.AppendLine("\t\t\tVulkanCheck(dispatch.vkEnumerateInstanceLayerProperties(&layerCount,ptr));");
			builder.AppendLine("\t\t}");
			builder.AppendLine("\t\tforeach(var layer in layerProperties) {");
			builder.AppendLine("\t\t\tif(global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8((nint)layer.layerName) == name) return true;");
			builder.AppendLine("\t\t}");
			builder.AppendLine("\t\treturn false;");
			builder.AppendLine("\t}");
			builder.AppendLine();

			builder.AppendLine("\tpublic static unsafe bool VulkanHasInstanceExtension(VulkanGlobalOnlyDispatch dispatch,string name) {");
			builder.AppendLine("\t\tuint extensionCount = 0;");
			builder.AppendLine("\t\tVulkanCheck(dispatch.vkEnumerateInstanceExtensionProperties(null,&extensionCount,null));");
			builder.AppendLine("\t\tvar extensionProperties = new VkExtensionProperties[extensionCount];");
			builder.AppendLine("\t\tfixed(VkExtensionProperties* ptr = extensionProperties) {");
			builder.AppendLine("\t\t\tVulkanCheck(dispatch.vkEnumerateInstanceExtensionProperties(null,&extensionCount,ptr));");
			builder.AppendLine("\t\t}");
			builder.AppendLine("\t\tforeach(var extension in extensionProperties) {");
			builder.AppendLine("\t\t\tif(global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8((nint)extension.extensionName) == name) return true;");
			builder.AppendLine("\t\t}");
			builder.AppendLine("\t\treturn false;");
			builder.AppendLine("\t}");
			builder.AppendLine();

			builder.AppendLine("\tpublic static unsafe void VulkanUnsignalSemaphore(VulkanInstanceOnlyDispatch dispatch,VkQueue queue,VkSemaphore semaphore) {");
			builder.AppendLine("\t\tvar stageFlags = (VkPipelineStageFlags)VkPipelineStageFlagBits.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;");
			builder.AppendLine("\t\tVkSubmitInfo submitInfo = new() {");
			builder.AppendLine("\t\t\tsType = VkStructureType.VK_STRUCTURE_TYPE_SUBMIT_INFO,");
			builder.AppendLine("\t\t\twaitSemaphoreCount = 1,");
			builder.AppendLine("\t\t\tpWaitSemaphores = &semaphore,");
			builder.AppendLine("\t\t\tpWaitDstStageMask = &stageFlags");
			builder.AppendLine("\t\t};");
			builder.AppendLine("\t\tVulkanCheck(dispatch.vkQueueSubmit(queue,1,&submitInfo,VkFence.Null));");
			builder.AppendLine("\t\tVulkanCheck(dispatch.vkQueueWaitIdle(queue));");
			builder.AppendLine("\t}");
			builder.AppendLine();*/

      var globalFunctions = Array.AsReadOnly([
        "PFN_vkEnumerateInstanceVersion",
        "PFN_vkEnumerateInstanceExtensionProperties",
        "PFN_vkEnumerateInstanceLayerProperties",
        "PFN_vkCreateInstance"
      ]);

      builder.AppendLine("\tpublic unsafe sealed class VulkanGlobalOnlyDispatch {");
      {
        foreach(var globalFunc in globalFunctions)
        {
          builder.AppendLine($"\t\tprivate {globalFunc} _{globalFunc.Replace("PFN_","")} = null;");
        }
        builder.AppendLine();
        builder.AppendLine("\t\tpublic VulkanGlobalOnlyDispatch(PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr) {");
        {
          builder.AppendLine("\t\t\tglobal::System.Diagnostics.Debug.Assert(vkGetInstanceProcAddr.ptr != null);");
          foreach(var globalFunc in globalFunctions)
          {
            var globalFuncName = globalFunc.Replace("PFN_","");
            builder.AppendLine($"\t\t\tfixed(byte* namePtr = \"{globalFuncName}\"u8) {{");
            builder.AppendLine($"\t\t\t\t_{globalFuncName} = ({globalFunc})vkGetInstanceProcAddr.ptr(VkInstance.Null,namePtr);");
            builder.AppendLine("\t\t\t}");
          }
        }
        builder.AppendLine("\t\t}");
        foreach(var globalFunc in globalFunctions)
        {
          var funcPointer = data.funcPointers[globalFunc];
          var globalFuncName = globalFunc.Replace("PFN_","");
          builder.AppendLine();
          builder.AppendLine($"\t\tpublic {funcPointer.returnType} {globalFuncName}({funcPointer.fullArgumentsString}) => _{globalFuncName}.ptr({funcPointer.argumentNamesString});");
        }
      }
      builder.AppendLine("\t}");
      builder.AppendLine();

      builder.AppendLine("\tpublic unsafe sealed class VulkanInstanceOnlyDispatch {");
      {
        foreach(var func in data.funcPointers.Keys)
        {
          if(data.funcPointers[func].isBaseType) continue;
          if(func == "PFN_vkGetInstanceProcAddr") continue;
          if(globalFunctions.Contains(func)) continue;
          builder.AppendLine($"\t\tprivate {func} _{func.Replace("PFN_","")} = null;");
        }
        builder.AppendLine();

        builder.AppendLine("\t\tpublic VulkanInstanceOnlyDispatch(PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr,VkInstance instance) {");
        {
          builder.AppendLine("\t\t\tglobal::System.Diagnostics.Debug.Assert(instance.value != VkInstance.Null.value);");
          builder.AppendLine("\t\t\tglobal::System.Diagnostics.Debug.Assert(vkGetInstanceProcAddr.ptr != null);");
          foreach(var func in data.funcPointers.Keys)
          {
            if(globalFunctions.Contains(func)) continue;
            if(data.funcPointers[func].isBaseType) continue;
            if(func == "PFN_vkGetInstanceProcAddr") continue;
            var globalFuncName = func.Replace("PFN_","");
            builder.AppendLine($"\t\t\tfixed(byte* namePtr = \"{globalFuncName}\"u8) {{");
            builder.AppendLine($"\t\t\t\t_{globalFuncName} = ({func})vkGetInstanceProcAddr.ptr(instance,namePtr);");
            builder.AppendLine("\t\t\t}");
          }
        }
        builder.AppendLine("\t\t}");

        foreach(var func in data.funcPointers.Keys)
        {
          if(data.funcPointers[func].isBaseType) continue;
          if(func == "PFN_vkGetInstanceProcAddr") continue;
          if(globalFunctions.Contains(func)) continue;
          var funcPointer = data.funcPointers[func];
          var globalFuncName = func.Replace("PFN_","");
          builder.AppendLine();
          builder.AppendLine($"\t\tpublic {funcPointer.returnType} {globalFuncName}({funcPointer.fullArgumentsString}) => _{globalFuncName}.ptr({funcPointer.argumentNamesString});");
        }
      }
      builder.AppendLine("\t}");
    }
    builder.AppendLine("}");
    context.AddSource(fileName,builder.ToString());
  }
}

internal class VulkanHeaderData
{
  public class Struct
  {
    public bool isUnion = false;
    public List<StructMember> members = [];
  }
  public class StructMember
  {
    public string name = "";
    public string type = "";
    public string arraySize = null;
    public string bitFields = null;
  }
  public class Constant
  {
    public string type = "";
    public string value = "";
  }
  public class FunctionParameter
  {
    public string type = "";
    public string name = "";
  }
  public class FunctionPointer
  {
    public bool isBaseType = false;
    public string returnType = "";
    public List<FunctionParameter> parameters = [];
    public string delegateUnmanagedString = "";
    public string fullArgumentsString = "";
    public string argumentNamesString = "";
  }
  public class Enum
  {
    public bool isFlags = false;
    public string underlyingType = "";
    public Dictionary<string,string> members = [];
  }

  public readonly List<string> comments = [];
  public readonly Dictionary<string,string> typeAliases = [];
  public readonly Dictionary<string,bool> handles = [];
  public readonly Dictionary<string,Struct> structs = [];
  public readonly Dictionary<string,Constant> constants = [];
  public readonly Dictionary<string,FunctionPointer> funcPointers = [];
  public readonly Dictionary<string,Enum> enums = [];
  public readonly Dictionary<string,uint> formatSizes = [];

  public readonly ReadOnlyCollection<string> typesThatCanBeUsedInFixedBuffers = Array.AsReadOnly(["bool","byte","char","short","int","long","sbyte","ushort","uint","ulong","float","double"]);

  private static string ReplaceBaseType(string type)
  {
    return type switch
    {
      "char" => "byte",
      "int8_t" => "sbyte",
      "uint8_t" => "byte",
      "int16_t" => "short",
      "uint16_t" => "ushort",
      "int32_t" => "int",
      "uint32_t" => "uint",
      "int64_t" => "long",
      "uint64_t" => "ulong",
      "size_t" => "ulong",
      "VkDeviceSize" => "ulong",
      "VkDeviceAddress" => "ulong",
      "VkFlags" => "uint",
      "VkFlags64" => "ulong",
      "VkSampleMask" => "uint",
      "VkBool32" => "uint",
      "HANDLE" => "void*",
      "HINSTANCE" => "void*",
      "HWND" => "void*",
      "HMONITOR" => "void*",
      "ANativeWindow" => "void",
      "AHardwareBuffer" => "void",
      "wl_display" => "void",
      "wl_surface" => "void",
      "Display" => "void",
      "Window" => "uint",
      "VisualID" => "uint",
      "xcb_connection_t" => "void",
      "xcb_window_t" => "uint",
      "xcb_visualid_t" => "uint",
      "IDirectFB" => "void",
      "IDirectFBSurface" => "void",
      "zx_handle_t" => "uint",
      "GgpStreamDescriptor" => "ulong",
      "GgpFrameToken" => "ulong",
      "_screen_context" => "void",
      "_screen_window" => "void",
      "_screen_buffer" => "void",
      "SECURITY_ATTRIBUTES" => "void",
      "DWORD" => "uint",
      "NvSciSyncAttrList" => "void*",
      "NvSciBufAttrList" => "void*",
      "NvSciBufObj" => "void*",
      "NvSciSyncObj" => "void*",
      "LPCWSTR" => "ushort*",
      "NvSciSyncFence" => "void",
      "CAMetalLayer" => "void",
      "OHNativeWindow" => "void",
      "OHBufferHandle" => "void",
      "OH_NativeBuffer" => "void",
      "MTLDevice_id" => "void*",
      "MTLCommandQueue_id" => "void*",
      "MTLBuffer_id" => "void*",
      "MTLTexture_id" => "void*",
      "IOSurfaceRef" => "void*",
      "MTLSharedEvent_id" => "void*",
      "VkRemoteAddressNV" => "void*",
      "RROutput" => "uint",
      var v => v
    };
  }

  private static StructMember ParseXmlStructMember(XmlElement element)
  {
    var typeStr = "";
    var nameStr = "";
    foreach(var child in element.ChildNodes.OfType<XmlNode>())
    {
      if(child is XmlElement childElement)
      {
        if(childElement.Name == "name")
        {
          nameStr = childElement.InnerText;
        }
        else if(childElement.Name == "type" || childElement.Name == "enum")
        {
          typeStr += childElement.InnerText;
        }
      }
      else if(child is XmlText childText)
      {
        typeStr += childText.InnerText;
      }
    }
    nameStr = nameStr.Trim();
    if(nameStr == "event") nameStr = "@event";
    if(nameStr == "object") nameStr = "@object";
    if(nameStr == "params") nameStr = "@params";

    typeStr = typeStr.Replace("const","").Replace("struct","").Replace("union","").Replace("enum","").Replace(" ","");
    var pointerIndex = typeStr.IndexOf('*');
    var leftBracketIndex = typeStr.IndexOf('[');
    var rightBracketIndex = typeStr.IndexOf(']');
    var colonIndex = typeStr.IndexOf(':');

    if(colonIndex != -1)
    {
      var targetType = typeStr.Substring(0,colonIndex);
      var bitfields = typeStr.Substring(colonIndex + 1);
      return new() { name = nameStr,type = ReplaceBaseType(targetType),bitFields = bitfields };
    }

    if(pointerIndex == -1 && leftBracketIndex == -1)
    {
      return new() { name = nameStr,type = ReplaceBaseType(typeStr) };
    }
    if(pointerIndex == -1 && leftBracketIndex != -1)
    {
      var arrayedType = typeStr.Substring(0,leftBracketIndex);
      var arraySize = typeStr.Substring(leftBracketIndex + 1,rightBracketIndex - leftBracketIndex - 1);
      return new() { name = nameStr,type = ReplaceBaseType(arrayedType),arraySize = arraySize };
    }
    if(pointerIndex != -1 && leftBracketIndex == -1)
    {
      var targetType = typeStr.Substring(0,pointerIndex);
      var asterisks = typeStr.Substring(pointerIndex);
      return new() { name = nameStr,type = ReplaceBaseType(targetType) + asterisks };
    }
    var innerType = typeStr.Substring(0,pointerIndex);
    var asterisks2 = typeStr.Substring(pointerIndex,leftBracketIndex - pointerIndex);
    var arraySize2 = typeStr.Substring(leftBracketIndex + 1,rightBracketIndex - leftBracketIndex - 1);
    return new() { name = nameStr,type = ReplaceBaseType(innerType) + asterisks2,arraySize = arraySize2 };
  }

  private static bool InvalidName(string name) => name.Contains("Video") || name.Contains("VIDEO");

  private static void ParseXmlFunction(VulkanHeaderData data,XmlElement functionElement,bool isBaseType)
  {
    var funcAliasAttr = functionElement.Attributes["alias"];
    if(funcAliasAttr != null)
    {
      var funcName = functionElement.Attributes["name"].Value;
      if(!funcName.StartsWith("PFN_")) funcName = "PFN_" + funcName;
      var funcAlias = funcAliasAttr.Value;
      if(!funcAlias.StartsWith("PFN_")) funcAlias = "PFN_" + funcAlias;
      data.typeAliases.Add(funcName,funcAlias);
      return;
    }
    var funcProto = ParseXmlStructMember(functionElement.ChildNodes.GetFirstElementByName("proto"));
    if(InvalidName(funcProto.name)) return;
    List<StructMember> funcParams = [];
    foreach(var paramNode in functionElement.ChildNodes.GetAllElementsByName("param"))
    {
      var paramApiAttr = paramNode.Attributes["api"];
      if(paramApiAttr != null && !paramApiAttr.Value.Split(',').Contains("vulkan")) continue;
      funcParams.Add(ParseXmlStructMember(paramNode));
    }
    if(!funcProto.name.StartsWith("PFN_")) funcProto.name = "PFN_" + funcProto.name;

    List<FunctionParameter> functionParameters = [.. funcParams.Select(element => new FunctionParameter() { name = element.name,type = element.type })];
    data.funcPointers[funcProto.name] = new()
    {
      isBaseType = isBaseType,
      returnType = funcProto.type,
      parameters = functionParameters,
      delegateUnmanagedString = "delegate* unmanaged<" + string.Join(",",[.. functionParameters.Select(element => element.type),funcProto.type]) + ">",
      fullArgumentsString = string.Join(",",[.. functionParameters.Select(element => element.type + " " + element.name)]),
      argumentNamesString = string.Join(",",[.. functionParameters.Select(element => element.name)])
    };
  }

  private static void ParseXmlTypes(VulkanHeaderData data,XmlElement typesElement)
  {
    foreach(var typeNode in typesElement.ChildNodes.GetAllElementsByName("type"))
    {
      var typeApiAttr = typeNode.Attributes["api"];
      if(typeApiAttr != null && !typeApiAttr.Value.Split(',').Contains("vulkan")) continue;

      var typeAlias = typeNode.Attributes["alias"];
      if(typeAlias != null)
      {
        var typeName = typeNode.Attributes["name"].Value;
        if(InvalidName(typeName)) continue;
        data.typeAliases[typeName] = typeAlias.Value;
        continue;
      }

      var typeCategoryAttr = typeNode.Attributes["category"];
      if(typeCategoryAttr == null) continue;
      if(typeCategoryAttr.Value == "handle")
      {
        var handleName = typeNode.ChildNodes.GetFirstElementByName("name").InnerText;
        if(InvalidName(handleName)) continue;
        var handleType = typeNode.ChildNodes.GetFirstElementByName("type").InnerText;
        data.handles[handleName] = handleType.Contains("NON_DISPATCHABLE");
      }
      else if(typeCategoryAttr.Value == "bitmask")
      {
        var bitmaskName = typeNode.ChildNodes.GetFirstElementByName("name").InnerText;
        if(InvalidName(bitmaskName)) continue;
        var bitmaskType = typeNode.ChildNodes.GetFirstElementByName("type").InnerText;
        data.enums[bitmaskName] = new() { isFlags = true,underlyingType = (bitmaskType == "VkFlags64" ? "long" : "int") };
      }
      else if(typeCategoryAttr.Value == "enum")
      {
        var typeName = typeNode.Attributes["name"].Value;
        if(InvalidName(typeName)) continue;
        data.enums[typeName] = new() { underlyingType = "int" };
      }
      else if(typeCategoryAttr.Value == "funcpointer")
      {
        ParseXmlFunction(data,typeNode,true);
      }
      else if(typeCategoryAttr.Value == "struct" || typeCategoryAttr.Value == "union")
      {
        var structName = typeNode.Attributes["name"].Value;
        if(InvalidName(structName)) continue;
        List<StructMember> structMembers = [];
        foreach(var memberNode in typeNode.ChildNodes.GetAllElementsByName("member"))
        {
          var memberApiAttr = memberNode.Attributes["api"];
          if(memberApiAttr != null && !memberApiAttr.Value.Split(',').Contains("vulkan")) continue;
          structMembers.Add(ParseXmlStructMember(memberNode));
        }
        data.structs[structName] = new() { isUnion = (typeCategoryAttr.Value == "union"),members = structMembers };
      }
    }
  }

  private static void ParseXmlEnums(VulkanHeaderData data,XmlElement enumsElement)
  {
    var enumsApiAttr = enumsElement.Attributes["api"];
    if(enumsApiAttr != null && !enumsApiAttr.Value.Split(',').Contains("vulkan")) return;

    var enumType = enumsElement.Attributes["type"].Value;
    if(enumType == "constants")
    {
      foreach(var constantElement in enumsElement.ChildNodes.GetAllElementsByName("enum"))
      {
        var constantType = constantElement.Attributes["type"].Value;
        var constantValue = constantElement.Attributes["value"].Value;
        var constantName = constantElement.Attributes["name"].Value;
        constantValue = constantValue.Replace("F","f").Replace("U","u").Replace("LL","l").Replace("L","").Trim('(',')');
        constantType = constantType.Replace("uint32_t","uint").Replace("uint64_t","ulong");
        data.constants.Add(constantName,new() { type = constantType,value = constantValue });
      }
    }
    else if(enumType == "enum" || enumType == "bitmask")
    {
      var enumName = enumsElement.Attributes["name"].Value;
      if(!InvalidName(enumName))
      {
        var @enum = data.enums[enumName];
        @enum.isFlags = (enumType == "bitmask");
        var enumBitwidthAttr = enumsElement.Attributes["bitwidth"];
        var enumBitwidth = 32;
        if(enumBitwidthAttr != null && enumBitwidthAttr.Value == "64")
        {
          enumBitwidth = 64;
          @enum.underlyingType = "long";
        }

        foreach(var enumElement in enumsElement.ChildNodes.GetAllElementsByName("enum"))
        {
          var enumElementName = enumElement.Attributes["name"].Value;
          if(InvalidName(enumElementName)) continue;
          var enumElementValueAttr = enumElement.Attributes["value"];
          var enumElementBitposAttr = enumElement.Attributes["bitpos"];
          var enumElementAliasAttr = enumElement.Attributes["alias"];

          if(enumElementAliasAttr != null)
          {
            @enum.members[enumElementName] = enumElementAliasAttr.Value;
          }
          else if(enumElementValueAttr != null)
          {
            @enum.members[enumElementName] = enumElementValueAttr.Value;
          }
          else if(enumElementBitposAttr != null)
          {
            if(enumBitwidth == 64)
            {
              @enum.members[enumElementName] = $"1L << {enumElementBitposAttr.Value}";
            }
            else
            {
              @enum.members[enumElementName] = $"1 << {enumElementBitposAttr.Value}";
            }
          }
        }
      }
    }
  }

  private static void ParseXmlCommands(VulkanHeaderData data,XmlElement commandsElement)
  {
    foreach(var commandElement in commandsElement.ChildNodes.GetAllElementsByName("command"))
    {
      var commandExportAttr = commandElement.Attributes["export"];
      if(commandExportAttr != null && !commandExportAttr.Value.Split(',').Contains("vulkan")) continue;
      ParseXmlFunction(data,commandElement,false);
    }
  }

  private static void ParseXmlFeature(VulkanHeaderData data,XmlElement featureElement)
  {
    var featureApiAttr = featureElement.Attributes["api"];
    if(featureApiAttr != null && !featureApiAttr.Value.Split(',').Contains("vulkan")) return;

    foreach(var requireElement in featureElement.ChildNodes.GetAllElementsByName("require"))
    {
      foreach(var enumElement in requireElement.ChildNodes.GetAllElementsByName("enum"))
      {
        var name = enumElement.Attributes["name"].Value;
        var valueAttr = enumElement.Attributes["value"];
        var extendsAttr = enumElement.Attributes["extends"];
        if(extendsAttr == null)
        {
          if(valueAttr != null)
          {
            data.constants[name] = new() { value = valueAttr.Value,type = valueAttr.Value.Contains('\"') ? "string" : "int" };
          }
          continue;
        }
        var extends = extendsAttr.Value;
        if(InvalidName(extends)) continue;

        var dirAttr = enumElement.Attributes["dir"];
        var dir = (dirAttr != null) ? dirAttr.Value : "";

        var offsetAttr = enumElement.Attributes["offset"];
        var extnumberAttr = enumElement.Attributes["extnumber"];
        var bitposAttr = enumElement.Attributes["bitpos"];
        var aliasAttr = enumElement.Attributes["alias"];

        var @enum = data.enums[extends];
        if(aliasAttr != null)
        {
          @enum.members[name] = aliasAttr.Value;
        }
        else if(extnumberAttr != null)
        {
          @enum.members[name] = $"{dir}1000{int.Parse(extnumberAttr.Value) - 1:D3}{int.Parse(offsetAttr.Value):D3}";
        }
        else if(valueAttr != null)
        {
          @enum.members[name] = valueAttr.Value;
        }
        else if(bitposAttr != null)
        {
          if(@enum.underlyingType == "long")
          {
            @enum.members[name] = $"1L << {bitposAttr.Value}";
          }
          else
          {
            @enum.members[name] = $"1 << {bitposAttr.Value}";
          }
        }
      }
    }
  }

  private static void ParseXmlExtensions(VulkanHeaderData data,XmlElement extensionsElement)
  {
    foreach(var extensionElement in extensionsElement.ChildNodes.GetAllElementsByName("extension"))
    {
      var featureSupportedAttr = extensionElement.Attributes["supported"];
      if(featureSupportedAttr != null && !featureSupportedAttr.Value.Split(',').Contains("vulkan")) continue;

      var extensionNumberAttr = extensionElement.Attributes["number"];

      foreach(var requireElement in extensionElement.ChildNodes.GetAllElementsByName("require"))
      {
        foreach(var enumElement in requireElement.ChildNodes.GetAllElementsByName("enum"))
        {
          var name = enumElement.Attributes["name"].Value;
          var extendsAttr = enumElement.Attributes["extends"];
          var offsetAttr = enumElement.Attributes["offset"];
          var bitposAttr = enumElement.Attributes["bitpos"];
          var valueAttr = enumElement.Attributes["value"];
          var aliasAttr = enumElement.Attributes["alias"];

          if(extendsAttr == null)
          {
            if(valueAttr != null)
            {
              data.constants[name] = new() { value = valueAttr.Value,type = valueAttr.Value.Contains('\"') ? "string" : "int" };
            }
            continue;
          }
          var extends = extendsAttr.Value;
          if(InvalidName(extends)) continue;

          var dirAttr = enumElement.Attributes["dir"];
          var dir = (dirAttr != null) ? dirAttr.Value : "";
          var @enum = data.enums[extends];
          if(aliasAttr != null)
          {
            @enum.members[name] = aliasAttr.Value;
          }
          else if(offsetAttr != null)
          {
            @enum.members[name] = $"{dir}1000{int.Parse(extensionNumberAttr.Value) - 1:D3}{int.Parse(offsetAttr.Value):D3}";
          }
          else if(valueAttr != null)
          {
            @enum.members[name] = valueAttr.Value;
          }
          else if(bitposAttr != null)
          {
            if(@enum.underlyingType == "long")
            {
              @enum.members[name] = $"1L << {bitposAttr.Value}";
            }
            else
            {
              @enum.members[name] = $"1 << {bitposAttr.Value}";
            }
          }
        }
      }
    }
  }

  public static void ParseXmlFormats(VulkanHeaderData data,XmlElement formatsElement)
  {
    foreach(var formatElement in formatsElement.ChildNodes.GetAllElementsByName("format"))
    {
      var nameValue = formatElement.Attributes["name"].Value;
      var classValue = formatElement.Attributes["class"].Value.TrimStart();
      if(classValue.StartsWith("8-bit"))
      {
        data.formatSizes.Add(nameValue,1);
      }
      else if(classValue.StartsWith("16-bit"))
      {
        data.formatSizes.Add(nameValue,2);
      }
      else if(classValue.StartsWith("24-bit"))
      {
        data.formatSizes.Add(nameValue,3);
      }
      else if(classValue.StartsWith("32-bit"))
      {
        data.formatSizes.Add(nameValue,4);
      }
      else if(classValue.StartsWith("48-bit"))
      {
        data.formatSizes.Add(nameValue,6);
      }
      else if(classValue.StartsWith("64-bit"))
      {
        data.formatSizes.Add(nameValue,8);
      }
      else if(classValue.StartsWith("96-bit"))
      {
        data.formatSizes.Add(nameValue,12);
      }
      else if(classValue.StartsWith("128-bit"))
      {
        data.formatSizes.Add(nameValue,16);
      }
      else if(classValue.StartsWith("192-bit"))
      {
        data.formatSizes.Add(nameValue,24);
      }
      else if(classValue.StartsWith("256-bit"))
      {
        data.formatSizes.Add(nameValue,32);
      }
    }
  }

  public static VulkanHeaderData CreateFrom(XmlDocument xmlDocument)
  {
    VulkanHeaderData data = new();
    foreach(var child in xmlDocument.DocumentElement.ChildNodes.OfType<XmlElement>())
    {
      if(child.Name == "types")
      {
        ParseXmlTypes(data,child);
      }
      else if(child.Name == "enums")
      {
        ParseXmlEnums(data,child);
      }
      else if(child.Name == "commands")
      {
        ParseXmlCommands(data,child);
      }
      else if(child.Name == "feature")
      {
        ParseXmlFeature(data,child);
      }
      else if(child.Name == "extensions")
      {
        ParseXmlExtensions(data,child);
      }
      else if(child.Name == "formats")
      {
        ParseXmlFormats(data,child);
      }
    }
    return data;
  }
}

file static class CollectionsExtensions
{
  public static XmlElement GetFirstElementByName(this XmlNodeList nodeList,string name)
  {
    return nodeList.OfType<XmlElement>().First(element => element.Name == name);
  }

  public static IEnumerable<XmlElement> GetAllElementsByName(this XmlNodeList nodeList,string name)
  {
    return nodeList.OfType<XmlElement>().Where(element => element.Name == name);
  }
}
